version: '3.8'

services:
  # Redis for session storage
  redis:
    image: redis:7-alpine
    container_name: session-mgmt-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
